### PR TITLE
Idle the ts while the display is off but the device is not locked

### PR DESCRIPTION
**Pull request by IMbackK**
Disable modem RSSI reporting while the display is off

### CODE REVIEW

**Comment by IMbackK** [comment]
this dosent ajust the debian package files to acutely install this, since idk how right now.

**Comment by MerlijnWajer** [comment]
@parazyd - what do you think?

Seems reasonable to me.

**Comment by parazyd** [comment]
@MerlijnWajer @IMbackK, Do our other devices support this same behaviour? If so, we might want to unify this somehow.

**Comment by IMbackK** [comment]
regarding the ts: other ts drivers can support runtime-pm and this is a standard kernel interface, however implementation details and  device discovery concerns preclude doing this in a totally generic fashion. That said a semi generic method, configured using mce's 70-$DEVICE.ini approach using a new mce module would be possible, and likely preferable.

Regarding the modem, i dont know in how far this can be generalized, i suspect it cant reasonable be at all.

**Comment by parazyd** [comment]
@MerlijnWajer @IMbackK, do you think it makes more sense to do this in mce then?

While we will probably end up with separate powermanagement packages with every device, we might also prefer to do something generic where possible.

**Comment by parazyd** [comment]
Hm yeah, it's not ideal since it's only 2GB in size.
I'll lurk more.

**Pull request closed without merging**
